version: "3.8"

services:
  nginx:
    image: "nginx:1.25.2-alpine"
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/var/www/site
    depends_on:
      - mysql
      - php
    restart: unless-stopped
    networks:
      - base-net

  php:
    build:
      context: docker
      dockerfile: ./fpm/Dockerfile
    container_name: php
    volumes:
      - ./public/:/var/www/site
      - ./docker/fpm/php.ini:/usr/local/etc/php/php.ini
    restart: unless-stopped
    networks:
      - base-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: site_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/database:/var/lib/mysql
    restart: unless-stopped
    networks:
      - base-net

  pma:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - base-net

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
    networks:
      - base-net

volumes:
  database:

networks:
  base-net:
    driver: bridge
